### ISSUE TITLE
getting Error while Adding bb layers 

### ISSUE THREAD

**Issue by hardikharpal** [WebPlatformForEmbedded/meta-wpe#151]
I am following your steps in My Ubuntu 16.04 LTS in virtual box  gettign following error...

`hardik@hardik-VirtualBox:~/rpi-yocto/rpi-ml-build$ bitbake-layers add-layer ../meta-raspberrypi
NOTE: Starting bitbake server...
ERROR: Unable to start bitbake server
ERROR: Last 10 lines of server log /home/hardik/rpi-yocto/rpi-ml-build/bitbake-cookerdaemon.log:
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
`

full log here ..

`Starting bitbake server pid 3314
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 3324
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 3338
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 15767
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 15782
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 2272
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 2345
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 2401
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 2446
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 2464
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 2471
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 3121
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
Starting bitbake server pid 3242
[1;31mERROR[0m: [31mThe following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  chrpath makeinfo[0m
Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 296, in parseBaseConfiguration
    bb.event.fire(bb.event.ConfigParsed(), self.data)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 218, in fire
    fire_class_handlers(event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 235, in base_eventhandler
    setup_hosttools_dir(d.getVar('HOSTTOOLS_DIR'), 'HOSTTOOLS', d)
  File "/home/hardik/rpi-yocto/poky/meta/classes/base.bbclass", line 132, in setup_hosttools_dir
    bb.fatal("The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:\n  %s" % " ".join(notfound))
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 104, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 77, in createDaemon
    function()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 403, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset, self.readypipein)
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 197, in __init__
    self.initConfigurationData()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/hardik/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException`

**Comment by kraj** [comment]
you should install chrpath makeinfo on your build system.

**Comment by hardikharpal** [comment]
@kraj Thank you

**Comment by rapveen** [comment]
Yes, it did work for me!!

**Comment by eariko** [comment]
Works perfectly
